// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqn31sBtELWHOiJrBFXhU5oGfOliz00Nk',
    appId: '1:921510261948:web:f3b95c0958fff21ffb0cb9',
    messagingSenderId: '921510261948',
    projectId: 'urbanito-365d8',
    authDomain: 'urbanito-365d8.firebaseapp.com',
    storageBucket: 'urbanito-365d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6i49AmbZYp21dZUGBNhD4zXBNjeOT5-g',
    appId: '1:921510261948:android:53feec7feaf34338fb0cb9',
    messagingSenderId: '921510261948',
    projectId: 'urbanito-365d8',
    storageBucket: 'urbanito-365d8.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqn31sBtELWHOiJrBFXhU5oGfOliz00Nk',
    appId: '1:921510261948:web:8d4dbb85620f6d18fb0cb9',
    messagingSenderId: '921510261948',
    projectId: 'urbanito-365d8',
    authDomain: 'urbanito-365d8.firebaseapp.com',
    storageBucket: 'urbanito-365d8.appspot.com',
  );
}
